services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    pull_policy: build
    ports:
      - "32769:3000"
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - catalog-data:/app/data
    restart: unless-stopped

volumes:
  catalog-data:
